services:
    shapecode_matomo.twig_extension:
        class: Shapecode\Bundle\MatomoBundle\Twig\Extension\MatomoExtension
        public: false
        arguments:
            - '@request_stack'
            - '%shapecode_matomo.template%'
            - '%shapecode_matomo.disabled%'
            - '%shapecode_matomo.no_script_tracking%'
            - '%shapecode_matomo.site_id%'
            - '%shapecode_matomo.host_name%'
            - '%shapecode_matomo.host_path%'
        tags:
            - { name: twig.extension }
